import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { publishCandidateOciArtifact } from "./publish-candidate-oci-artifact.mjs";
import { buildCandidateOciArtifactDescriptor } from "./build-candidate-oci-artifact-descriptor.mjs";

const hash = (bytes) => createHash("sha256").update(bytes).digest("hex");
test("payload 전량 conditional create·GET readback 뒤 descriptor를 마지막으로 저장한다", async () => {
  const fixture = await createFixture(); const calls = []; const stored = new Map();
  const client = { identity: { namespace: "namespace", bucket: "candidate-private" }, async putObjectIfAbsent(key, bytes) { calls.push(`put:${key}`); if (stored.has(key)) return false; stored.set(key, Buffer.from(bytes)); return true; }, async readObject(key) { calls.push(`get:${key}`); return stored.has(key) ? { exists: true, body: stored.get(key) } : { exists: false }; } };
  try { const result = await publishCandidateOciArtifact({ root: fixture.root, descriptor: fixture.descriptorPath, client }); assert.equal(result.artifactId, hash(await readFile(fixture.descriptorPath))); assert.equal(calls.at(-2).startsWith("put:candidates/v1/runs/42/"), true); assert.equal(calls.at(-1).startsWith("get:candidates/v1/runs/42/"), true); assert.equal([...stored].length, 7); } finally { await fixture.cleanup(); }
});
test("payload readback failure는 descriptor write와 success를 만들지 않는다", async () => {
  const fixture = await createFixture(); const calls = []; const client = { identity: { namespace: "namespace", bucket: "candidate-private" }, async putObjectIfAbsent(key) { calls.push(`put:${key}`); return true; }, async readObject(key) { calls.push(`get:${key}`); return { exists: true, body: Buffer.from("wrong") }; } };
  try { await assert.rejects(publishCandidateOciArtifact({ root: fixture.root, descriptor: fixture.descriptorPath, client })); assert.equal(calls.filter((call) => call.startsWith("put:")).length, 1); } finally { await fixture.cleanup(); }
});
test("publisher는 builder 결과라도 현재 stage의 forbidden evidence·descriptor expiry drift를 PUT 전에 다시 거부한다", async () => {
  for (const mutate of [
    async (fixture) => writeFile(path.join(fixture.root, "release-decision.json"), "blocked\n"),
    async (fixture) => { const value = JSON.parse(await readFile(fixture.descriptorPath, "utf8")); value.createdAt = "2026-08-25T00:00:00.000Z"; await writeFile(fixture.descriptorPath, `${JSON.stringify(value)}\n`); },
  ]) { const fixture = await createFixture(); const calls = []; const client = { identity: { namespace: "namespace", bucket: "candidate-private" }, async putObjectIfAbsent() { calls.push("put"); return true; }, async readObject() { calls.push("get"); return { exists: false }; } }; try { await mutate(fixture); await assert.rejects(publishCandidateOciArtifact({ root: fixture.root, descriptor: fixture.descriptorPath, client })); assert.deepEqual(calls, []); } finally { await fixture.cleanup(); } }
});
async function createFixture() { const root = await mkdtemp(path.join(os.tmpdir(), "candidate-oci-publish-")); const catalog = path.join(root, "catalog"); await mkdir(catalog); const manifest = Buffer.from("{\"manifestVersion\":2}\n"), provenance = Buffer.from("{\"candidateBuild\":true}\n"), pack = Buffer.from("pack\n"); await Promise.all([writeFile(path.join(catalog, "current.json"), manifest), writeFile(path.join(root, "current.provenance.json"), provenance), writeFile(path.join(catalog, "capital.sqlite.gz"), pack)]); const tuplePath = path.join(root, "datapack-candidate-tuple.json"); const tuple = { candidateBinding: { candidateId: "candidate-1", buildSpecSha256: "b".repeat(64), manifestSha256: hash(manifest) }, freshnessExpiresAt: "2026-08-25T00:00:00.000Z" }; await writeFile(tuplePath, `${JSON.stringify(tuple)}\n`); const inventoryPath = path.join(root, "data-artifact-inventory.json"), componentPath = path.join(root, "data-component-manifest.json"); const listed = ["catalog/capital.sqlite.gz", "catalog/current.json", "current.provenance.json", "datapack-candidate-tuple.json"].map(async (item) => { const bytes = await readFile(path.join(root, item)); return { path: item, sizeBytes: bytes.length, sha256: hash(bytes) }; }); const inventory = { schemaVersion: 1, artifactKind: "datapack-candidate-inventory", entries: (await Promise.all(listed)).sort((a, b) => a.path.localeCompare(b.path)) }; const inventoryBytes = Buffer.from(`${JSON.stringify(inventory, null, 2)}\n`); const component = { schemaVersion: 1, component: "data", repository: "AquilaXk/easysubway-data", gitSha: "a".repeat(40), workflowRunId: "42", dataVersion: "1", releaseSequence: 1, manifestSha256: hash(manifest), provenance: { sourceSnapshotSetHash: "c".repeat(64) }, artifactInventorySha256: hash(inventoryBytes), contractVersion: "datapack-contract-v3", issueRef: "AquilaXk/easysubway-data#529" }; await Promise.all([writeFile(inventoryPath, inventoryBytes), writeFile(componentPath, `${JSON.stringify(component)}\n`)]); const descriptorPath = `${root}.descriptor.json`; await buildCandidateOciArtifactDescriptor({ root, tuple: tuplePath, inventory: inventoryPath, component: componentPath, repository: "AquilaXk/easysubway-data", workflowRunId: "42", headSha: "a".repeat(40), namespace: "namespace", bucket: "candidate-private", createdAt: "2026-08-24T00:00:00.000Z", output: descriptorPath }); return { root, descriptorPath, cleanup: async () => { await rm(descriptorPath, { force: true }); await rm(root, { recursive: true, force: true }); } }; }
