import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const modulePath = path.join(root, "tools/ci/decide-current-seoul-accessibility-refresh.mjs");
async function load() { return import(`${pathToFileURL(modulePath).href}?test=${Date.now()}`); }
async function fixture({ freshUntil = "2026-08-30T12:00:00.000Z" } = {}) { const directory = await mkdtemp(path.join(os.tmpdir(), "seoul-refresh-decision-")); const inventoryPath = path.join(directory, "inventory.json"); const policyPath = path.join(directory, "policy.json"); const prsPath = path.join(directory, "prs.json"); const claimsPath = path.join(directory, "claims.txt"); await writeFile(inventoryPath, JSON.stringify({ sources: [{ id: "seoul-metro-accessibility", accessibilityAdmissionEvidence: { freshUntil } }] })); await writeFile(policyPath, JSON.stringify({ monitoring: { alertBeforePackExpiry: "PT6H" } })); await writeFile(prsPath, "[]"); await writeFile(claimsPath, ""); return { inventoryPath, policyPath, prsPath, claimsPath, repository: "AquilaXk/easysubway-data" }; }
test("Seoul refresh decision distinguishes due states from the configured threshold", async () => { const { decideCurrentSeoulAccessibilityRefresh } = await load(); const input = await fixture(); for (const [now, state] of [["2026-08-30T05:59:59.999Z", "NOT_DUE"], ["2026-08-30T06:00:00.000Z", "DUE"], ["2026-08-30T12:00:00.000Z", "EXPIRED"]]) assert.equal((await decideCurrentSeoulAccessibilityRefresh({ ...input, now: new Date(now) })).state, state); });
test("Seoul refresh decision accepts only a same-repository main PR and recovers one claim", async () => { const { decideCurrentSeoulAccessibilityRefresh } = await load(); const input = await fixture(); await writeFile(input.prsPath, JSON.stringify([{ state: "OPEN", isDraft: true, headRefName: "automation/639-seoul-accessibility-refresh-1", baseRefName: "main", headRepository: { nameWithOwner: input.repository }, isCrossRepository: false }])); assert.equal((await decideCurrentSeoulAccessibilityRefresh({ ...input, now: new Date("2026-08-30T07:00:00.000Z") })).state, "OPEN_PR"); await writeFile(input.prsPath, "[]"); await writeFile(input.claimsPath, "0123456789abcdef0123456789abcdef01234567\trefs/heads/automation/639-seoul-accessibility-refresh-1\n"); assert.deepEqual(await decideCurrentSeoulAccessibilityRefresh({ ...input, now: new Date("2026-08-30T07:00:00.000Z") }), { state: "RECOVER_CLAIM", alertBeforePackExpiry: "PT6H", branch: "automation/639-seoul-accessibility-refresh-1" }); });
