import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const workflowPath = path.join(root, ".github/workflows/kric-exit-full-capital-refresh.yml");

test("EXIT refresh keeps exact-main OCI producer, immutable recovery, and selected FACILITY terminal consumer separate", () => {
  assert.ok(existsSync(workflowPath));
  const yml = readFileSync(workflowPath, "utf8");
  assert.match(yml, /cron: "41 \*\/2 \* \* \*"/);
  assert.match(yml, /github\.ref == 'refs\/heads\/main'/);
  assert.match(yml, /permissions:\n  actions: read\n  contents: read\n  pull-requests: read/);
  assert.match(yml, /source:\n    name: Produce immutable EXIT source[\s\S]*?permissions:\n      actions: read\n      contents: write\n      pull-requests: read/);
  assert.match(yml, /terminal:\n    name: Commit verified EXIT terminal candidate[\s\S]*?permissions:\n      actions: read\n      contents: write/);
  assert.match(yml, /decide-current-kric-exit-full-capital-refresh\.mjs/);
  assert.match(yml, /--json number,state,isDraft,headRefName,headRefOid,baseRefName,headRepository,isCrossRepository,files/);
  const normalizeCommand = 'git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"';
  const normalizeOrigin = yml.indexOf(normalizeCommand);
  const createClaim = yml.indexOf('git switch -c "${branch}"');
  assert.ok(normalizeOrigin >= 0 && normalizeOrigin < createClaim);
  const terminalJob = yml.indexOf("\n  terminal:");
  const normalizeTerminalOrigin = yml.indexOf(normalizeCommand, normalizeOrigin + normalizeCommand.length);
  const terminalFetch = yml.indexOf('git fetch --no-tags origin "refs/heads/${EXIT_REFRESH_FACILITY_BRANCH}:refs/remotes/origin/${EXIT_REFRESH_FACILITY_BRANCH}"', terminalJob);
  assert.ok(normalizeTerminalOrigin > terminalJob && normalizeTerminalOrigin < terminalFetch);
  assert.equal(yml.indexOf(normalizeCommand, normalizeTerminalOrigin + normalizeCommand.length), -1);
  assert.match(yml, /runCurrentCapitalExitOnlyProducer/);
  assert.match(yml, /repositorySha: process\.env\.EXIT_REFRESH_MAIN_SHA/);
  assert.match(yml, /facilityPullRequest: \{ repository: process\.env\.GITHUB_REPOSITORY, branch: process\.env\.EXIT_REFRESH_FACILITY_BRANCH, headSha: process\.env\.EXIT_REFRESH_FACILITY_HEAD_SHA \}/);
  assert.match(yml, /name: kric-exit-full-capital-source-\$\{\{ github\.run_id \}\}/);
  assert.match(yml, /current-kric-exit-provider-oci-plan\.json/);
  assert.match(yml, /current-kric-exit-provider-oci-receipt\.json/);
  assert.match(yml, /current-capital-exit-provider-source-handoff\.json/);
  assert.match(yml, /retention-days: 14/);
  assert.match(yml, /require-workflow-artifact\.mjs/);
  assert.match(yml, /actions\/runs\/\$\{producer_run_id\}/);
  assert.match(yml, /head_repository\?\.full_name/);
  assert.match(yml, /name: Produce immutable EXIT source/);
  assert.match(yml, /name: Commit verified EXIT terminal candidate/);
  assert.match(yml, /jobs\[0\]\.conclusion !== "success"/);
  assert.match(yml, /needs\.source\.outputs\.producer_run_id/);
  assert.match(yml, /\.github\/workflows\/kric-exit-full-capital-refresh\.yml/);
  assert.match(yml, /gh run download "\$\{producer_run_id\}"/);
  assert.match(yml, /recover-current-live-chain-transfer-observation\.mjs/);
  assert.match(yml, /git worktree add --detach "\$\{transfer_source_root\}" "\$\{EXIT_REFRESH_FACILITY_HEAD_SHA\}"/);
  assert.match(yml, /git worktree remove --force "\$\{transfer_source_root\}"/);
  assert.match(yml, /runCurrentCapitalExitTerminalConsumer/);
  assert.match(yml, /candidateOperationId: `kric-exit-full-capital-terminal-\$\{process\.env\.GITHUB_RUN_ID\}`/);
  assert.match(yml, /git fetch --no-tags origin "refs\/heads\/\$\{EXIT_REFRESH_FACILITY_BRANCH\}:refs\/remotes\/origin\/\$\{EXIT_REFRESH_FACILITY_BRANCH\}"/);
  assert.match(yml, /git switch --track -c "\$\{EXIT_REFRESH_FACILITY_BRANCH\}" "origin\/\$\{EXIT_REFRESH_FACILITY_BRANCH\}"/);
  assert.match(yml, /currentCapitalLiveChainOutputPaths/);
  assert.match(yml, /current-capital-live-chain-fan-in\.json/);
  assert.match(yml, /current-capital-accessibility-transition\.json/);
  assert.match(yml, /current-capital-accessibility-transition-successor\.json/);
  assert.match(yml, /git rm -- "\$\{markers\[@\]\}"/);
  assert.match(yml, /git commit -m "Refresh KRIC EXIT full-capital snapshot"/);
  const terminalPush = yml.indexOf('git push origin "${EXIT_REFRESH_FACILITY_BRANCH}"');
  assert.ok(terminalPush > yml.lastIndexOf("gh auth setup-git", terminalPush));
  assert.match(yml, /\[\[ "\$\{remote_claim_sha\}" == "\$\{EXIT_REFRESH_CLAIM_SHA\}" \]\]/);
  assert.match(yml, /git push origin --delete "\$\{EXIT_REFRESH_BRANCH\}"/);
  assert.ok(yml.indexOf('git push origin --delete "${EXIT_REFRESH_BRANCH}"') > terminalPush);
  assert.doesNotMatch(yml, /gh pr create/);
  assert.doesNotMatch(yml, /aws|s3:|fallback|previous|stale|composite|legacy|automerge|approval|gh pr merge|git merge|git push origin main/i);
});
