import test from "node:test";
import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const workflowPath = path.join(root, ".github/workflows/kric-exit-full-capital-refresh.yml");

test("EXIT refresh keeps exact-main OCI producer, immutable recovery, and selected FACILITY terminal consumer separate", () => {
  assert.ok(existsSync(workflowPath));
  const yml = readFileSync(workflowPath, "utf8");
  assert.match(yml, /cron: "41 \*\/2 \* \* \*"/);
  assert.match(yml, /recovery_producer_run_id:/);
  assert.match(yml, /INSPECT_SELECTED_CLAIM/);
  assert.match(yml, /INSPECTED_ANCESTOR_CLAIM/);
  assert.match(yml, /--recovery-producer-run-id "\$\{recovery_producer_run_id\}"/);
  assert.match(yml, /producer_run_id="\$\{\{ steps\.decision\.outputs\.producer_run_id \}\}"/);
  assert.match(yml, /\[\[ "\$\{branch\}" == "automation\/6-kric-exit-full-capital-refresh-\$\{producer_run_id\}" \]\]/);
  assert.match(yml, /git merge-base --is-ancestor "\$\{producer_main_sha\}" "\$\{current_main_sha\}"/);
  assert.match(yml, /git merge-base --is-ancestor "\$\{current_main_sha\}" "\$\{EXIT_REFRESH_FACILITY_HEAD_SHA\}"/);
  assert.match(yml, /rebuildCurrentCapitalTopologyTerminalHandoffForAncestorRecovery/);
  assert.match(yml, /github\.ref == 'refs\/heads\/main'/);
  assert.match(yml, /permissions:\n  actions: read\n  contents: read\n  pull-requests: read/);
  assert.match(yml, /source:\n    name: Produce immutable EXIT source[\s\S]*?permissions:\n      actions: read\n      contents: write\n      pull-requests: read/);
  assert.match(yml, /terminal:\n    name: Commit verified EXIT terminal candidate[\s\S]*?permissions:\n      actions: read\n      contents: write/);
  assert.match(yml, /decide-current-kric-exit-full-capital-refresh\.mjs/);
  assert.match(yml, /--json number,state,isDraft,headRefName,headRefOid,baseRefName,headRepository,isCrossRepository,files/);
  assert.match(yml, /claim-evidence\.json/);
  assert.match(yml, /git fetch --no-tags origin "\$\{claim_ref\}"/);
  assert.match(yml, /git rev-parse "\$\{claim_sha\}\^"/);
  assert.match(yml, /git rev-list --count "\$\{main_sha\}\.\.\$\{claim_sha\}"/);
  assert.match(yml, /git show -s --format=%s "\$\{claim_sha\}"/);
  assert.match(yml, /\.split\("\\n"\)\.filter\(Boolean\)/);
  assert.match(yml, /const fields = line\.split\("\\t"\);/);
  assert.match(yml, /if \(fields\.length !== 5\) throw new Error\("invalid claim evidence field count"\);/);
  assert.match(yml, /JSON\.stringify\(rows\) \+ "\\n"/);
  assert.doesNotMatch(yml, /split\("\\\\(?:n|t)"\)|\+ "\\\\n"/);
  assert.match(yml, /--claim-evidence "\$\{claim_evidence\}"/);
  assert.match(yml, /--current-main-sha "\$\{main_sha\}"/);
  const normalizeCommand = 'git remote set-url origin "https://github.com/${GITHUB_REPOSITORY}.git"';
  const normalizeOrigin = yml.indexOf(normalizeCommand);
  const boundFacilityFetch = yml.indexOf('git fetch --no-tags origin "refs/heads/${branch}:refs/remotes/origin/${branch}"');
  const preProviderAncestry = yml.indexOf('execFileSync("git", ["merge-base", "--is-ancestor", sourceMainSha, process.env.EXIT_REFRESH_FACILITY_HEAD_SHA]');
  const createClaim = yml.indexOf('git switch -c "${branch}"');
  assert.ok(normalizeOrigin >= 0 && normalizeOrigin < createClaim);
  const terminalJob = yml.indexOf("\n  terminal:");
  const normalizeTerminalOrigin = yml.indexOf(normalizeCommand, normalizeOrigin + normalizeCommand.length);
  const terminalFetch = yml.indexOf('git fetch --no-tags origin "refs/heads/${EXIT_REFRESH_FACILITY_BRANCH}:refs/remotes/origin/${EXIT_REFRESH_FACILITY_BRANCH}"', terminalJob);
  assert.ok(normalizeTerminalOrigin > terminalJob && normalizeTerminalOrigin < terminalFetch);
  assert.equal(yml.indexOf(normalizeCommand, normalizeTerminalOrigin + normalizeCommand.length), -1);
  assert.match(yml, /runCurrentCapitalExitOnlyProducer/);
  assert.match(yml, /repositorySha: process\.env\.EXIT_REFRESH_MAIN_SHA/);
  assert.match(yml, /facilityPullRequest: \{ repository: process\.env\.GITHUB_REPOSITORY, branch: process\.env\.EXIT_REFRESH_FACILITY_BRANCH, headSha: process\.env\.EXIT_REFRESH_FACILITY_HEAD_SHA \}/);
  assert.match(yml, /name: kric-exit-full-capital-source-\$\{\{ github\.run_id \}\}/);
  assert.match(yml, /current-kric-exit-provider-oci-plan\.json/);
  assert.match(yml, /current-kric-exit-provider-oci-receipt\.json/);
  assert.match(yml, /current-capital-exit-provider-source-handoff\.json/);
  assert.match(yml, /current-capital-topology-terminal-handoff\.json/);
  assert.match(yml, /private-builder\.bundle/);
  assert.match(yml, /retention-days: 14/);
  assert.match(yml, /require-workflow-artifact\.mjs/);
  assert.match(yml, /actions\/runs\/\$\{producer_run_id\}/);
  assert.match(yml, /head_repository\?\.full_name/);
  assert.match(yml, /name: Produce immutable EXIT source/);
  assert.match(yml, /name: Commit verified EXIT terminal candidate/);
  assert.match(yml, /jobs\[0\]\.conclusion !== "success"/);
  assert.match(yml, /needs\.source\.outputs\.producer_run_id/);
  assert.match(yml, /\.github\/workflows\/kric-exit-full-capital-refresh\.yml/);
  assert.match(yml, /gh run download "\$\{producer_run_id\}"/);
  assert.match(yml, /recover-current-live-chain-transfer-observation\.mjs/);
  assert.match(yml, /git worktree add --detach "\$\{transfer_source_root\}" "\$\{EXIT_REFRESH_FACILITY_HEAD_SHA\}"/);
  assert.match(yml, /git worktree add --detach "\$\{source_main_root\}" "\$\{EXIT_REFRESH_MAIN_SHA\}"/);
  assert.match(yml, /git worktree add --detach "\$\{private_builder_root\}" "\$\{EXIT_REFRESH_BUILDER_SHA\}"/);
  assert.match(yml, /git worktree remove --force "\$\{directory\}"/);
  const itxFreshnessPreflight = yml.indexOf("assertCurrentCapitalExitItxAuthorityFresh");
  const firstTopologyCollector = yml.indexOf("collect-capital-route-topology.mjs --download --output");
  const providerConfiguration = yml.indexOf("name: Validate provider and OCI configuration");
  assert.ok(boundFacilityFetch >= 0 && preProviderAncestry > boundFacilityFetch);
  assert.ok(preProviderAncestry < createClaim && preProviderAncestry < providerConfiguration && preProviderAncestry < firstTopologyCollector);
  assert.ok(itxFreshnessPreflight >= 0 && itxFreshnessPreflight < firstTopologyCollector);
  assert.equal((yml.match(/collect-capital-route-topology\.mjs --download --output/g) ?? []).length, 1);
  assert.equal((yml.match(/collect-incheon-station-info\.mjs --download --output/g) ?? []).length, 1);
  assert.equal((yml.match(/collect-incheon-timetable\.mjs --download/g) ?? []).length, 1);
  assert.match(yml, /private builder input count mismatch/);
  assert.match(yml, /git -C "\$\{private_builder_root\}" commit -m "Stage current topology inputs"/);
  assert.match(yml, /private builder parent mismatch/);
  assert.match(yml, /git bundle create/);
  assert.match(yml, /git bundle unbundle/);
  assert.match(yml, /export EXIT_REFRESH_RETAINED_ROOT="\$\{retained_root\}"/);
  assert.match(yml, /export EXIT_REFRESH_PRIVATE_BUILDER_ROOT="\$\{private_builder_root\}"/);
  assert.match(yml, /export EXIT_REFRESH_BUILDER_SHA="\$\{builder_sha\}"/);
  assert.match(yml, /retainedRoot: process\.env\.EXIT_REFRESH_RETAINED_ROOT/);
  assert.match(yml, /privateBuilderRoot: process\.env\.EXIT_REFRESH_PRIVATE_BUILDER_ROOT/);
  assert.match(yml, /builderGitSha: process\.env\.EXIT_REFRESH_BUILDER_SHA/);
  assert.match(yml, /topologyBuild: JSON\.parse\(await readFile/);
  assert.match(yml, /"private-builder" && "\$\{actual\}" == "\$\{EXIT_REFRESH_FACILITY_HEAD_SHA\}"/);
  assert.match(yml, /runCurrentCapitalExitTerminalConsumer/);
  assert.match(yml, /export EXIT_REFRESH_SOURCE_MAIN_ROOT="\$\{source_main_root\}"/);
  assert.match(yml, /sourceMainRoot: process\.env\.EXIT_REFRESH_SOURCE_MAIN_ROOT/);
  assert.match(yml, /sourceMainGitSha: process\.env\.EXIT_REFRESH_MAIN_SHA/);
  assert.match(yml, /privateBuilderRoot: process\.env\.EXIT_REFRESH_PRIVATE_BUILDER_ROOT/);
  assert.match(yml, /builderGitSha: process\.env\.EXIT_REFRESH_BUILDER_SHA/);
  assert.match(yml, /topologyBuild: topologyHandoff\.topologyBuild, topologyHandoffBytes/);
  assert.match(yml, /candidateOperationId: `kric-exit-full-capital-terminal-\$\{process\.env\.GITHUB_RUN_ID\}`/);
  assert.match(yml, /git fetch --no-tags origin "refs\/heads\/\$\{EXIT_REFRESH_FACILITY_BRANCH\}:refs\/remotes\/origin\/\$\{EXIT_REFRESH_FACILITY_BRANCH\}"/);
  assert.match(yml, /git switch --track -c "\$\{EXIT_REFRESH_FACILITY_BRANCH\}" "origin\/\$\{EXIT_REFRESH_FACILITY_BRANCH\}"/);
  assert.match(yml, /terminal_parent_sha="\$\{EXIT_REFRESH_BUILDER_SHA\}"/);
  assert.match(yml, /INSPECTED_ANCESTOR_CLAIM[\s\S]*?terminal_parent_sha="\$\{EXIT_REFRESH_FACILITY_HEAD_SHA\}"/);
  assert.match(yml, /git commit-tree "\$\{final_tree\}" -p "\$\{terminal_parent_sha\}"/);
  assert.match(yml, /git update-ref "refs\/heads\/\$\{EXIT_REFRESH_FACILITY_BRANCH\}" "\$\{final_sha\}" "\$\{EXIT_REFRESH_FACILITY_HEAD_SHA\}"/);
  assert.match(yml, /Refresh KRIC EXIT full-capital snapshot/);
  const terminalPush = yml.indexOf('git push origin "${EXIT_REFRESH_FACILITY_BRANCH}"');
  assert.ok(terminalPush > yml.lastIndexOf("gh auth setup-git", terminalPush));
  assert.match(yml, /\[\[ "\$\{remote_claim_sha\}" == "\$\{EXIT_REFRESH_CLAIM_SHA\}" \]\]/);
  assert.match(yml, /git push origin --delete "\$\{EXIT_REFRESH_BRANCH\}"/);
  assert.ok(yml.indexOf('git push origin --delete "${EXIT_REFRESH_BRANCH}"') > terminalPush);
  assert.equal((yml.match(/git push origin "\$\{EXIT_REFRESH_FACILITY_BRANCH\}"/g) ?? []).length, 1);
  assert.doesNotMatch(yml, /git rm -- "\$\{markers\[@\]}"/);
  assert.doesNotMatch(yml, /cp "\$\{staged_root\}/);
  assert.doesNotMatch(yml, /git reset --hard|git apply --index/);
  assert.doesNotMatch(yml, /itxCurrentAdmissionPath: null/);
  assert.doesNotMatch(yml, /run-current-itx-collection|DATA_GO_KR_SERVICE_KEY/);
  assert.doesNotMatch(yml, /gh pr create/);
  assert.doesNotMatch(yml, /aws|s3:|fallback|previous|stale|composite|legacy|automerge|approval|gh pr merge|git merge(?:\s|$)|git push origin main/i);
});
